#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/pagekite" ]; then
	update-rc.d pagekite defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d pagekite start || exit $?
	else
		/etc/init.d/pagekite start || exit $?
	fi
fi
# End automatically added section
