Document: pagekite
Title: Debian pagekite Manual
Author: <insert document author here>
Abstract: This manual describes what pagekite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pagekite/pagekite.sgml.gz

Format: postscript
Files: /usr/share/doc/pagekite/pagekite.ps.gz

Format: text
Files: /usr/share/doc/pagekite/pagekite.text.gz

Format: HTML
Index: /usr/share/doc/pagekite/html/index.html
Files: /usr/share/doc/pagekite/html/*.html
